config/routes.rb
Rails.application.routes.draw do
  root to: 'tubuyakis#new'
  resources :tubuyakis do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tubuyaki.rb
class Tubuyaki < ApplicationRecord
  validates :content, presence: true, length: { in: 1..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tubuyakis_controller.rb
class TubuyakisController < ApplicationController
  before_action :set_tubuyaki, only: [:edit,:destroy,:update,:show]

  def index
    @tubuyaki = Tubuyaki.all
  end

  def new
    @tubuyaki = Tubuyaki.new
  end

  def create
    @tubuyaki = Tubuyaki.new(tubuyaki_params)
    if @tubuyaki.save
      redirect_to tubuyakis_path, notice: "つぶやきました！"
    else
      render 'new'
    end
  end

  def show

  end

  def confirm
    @tubuyaki = Tubuyaki.new(tubuyaki_params)
  end

  def edit
    @tubuyaki = Tubuyaki.find(params[:id])
  end

  def update
    if @tubuyaki.update(tubuyaki_params)
      redirect_to tubuyakis_path, notice: "つぶやきを編集しました！"
    else
      render 'edit'
    end
  end


  def destroy
    @tubuyaki = Tubuyaki.find(params[:id])
    @tubuyaki.destroy
    redirect_to tubuyakis_path, notice: "つぶやきを消しました！"
  end

  private

  def tubuyaki_params
    params.require(:tubuyaki).permit(:content)
  end

  def set_tubuyaki
    @tubuyaki = Tubuyaki.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tubuyakis_helper.rb
module TubuyakisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tubuyakis/_form.html.erb
<html>
  <body>
    <header>
      <%= image_tag('japan.jpg') %>
    </header>
    <div class="main-contents">
      <%= form_with(model: @tubuyaki, local: true) do |form| %>
        <% if @tubuyaki.errors.any? %>
          <div id="error_explanation">
            <h2><%= @tubuyaki.errors.count %>件のエラーがあります。</h2>
            <ul>
              <% @tubuyaki.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="tubuyaki_title" %>
          <%= form.text_field :content %>
        </div>
        <%= form.submit("つぶやく")%>
        <br><%= link_to "つぶやき一覧をみる", tubuyakis_path %>
      <% end %>
    </div>
    <footer class="footer">
      <p>Copyright © 2019 TAKEYAMA INC All RIGHTS RESERVED.</p>
    </footer>
  </body>
</html>

app/views/tubuyakis/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @tubuyaki, url: tubuyakis_path, local: true) do |form| %>
  <%= form.hidden_field :content %>

  <p>本文:<%= @tubuyaki.content %></p>
  <%= form.submit  "つぶやく" %>
<% end %>

app/views/tubuyakis/edit.html.erb
<%= render 'form' %>

app/views/tubuyakis/index.html.erb
<h3>つぶやき一覧
  <br><%= link_to '何かつぶやく', new_tubuyaki_path %>
</h3>
<div class="contents">
  <% @tubuyaki.each do |tubuyaki| %>
    <br>
      <li>
        <%= tubuyaki.content %>
        <br><%= link_to 'つぶやきを編集する。', edit_tubuyaki_path(tubuyaki.id) %>
        <br><%= link_to 'つぶやきを消す。', tubuyaki_path(tubuyaki.id), method: :delete %>
      </li>
    </ul>
  <% end %>
</div>

app/views/tubuyakis/new.html.erb
<html>
  <body>
    <header>
      <%= image_tag('japan.jpg') %>
    </header>
    <div class="maine-contents">
      <%= form_with(model: @tubuyaki, local: true) do |form| %>
        <% if @tubuyaki.errors.any? %>
          <div id="error_explanation">
            <h2><%= @tubuyaki.errors.count %>件のエラーがあります。</h2>
            <ul>
              <% @tubuyaki.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
         <% end %>
        <div class="tubuyaki_title" %>
          <%= form.text_field :content %>
        </div>
        <%= form.submit("つぶやく")%>
        <br><%= link_to "つぶやき一覧をみる", tubuyakis_path %>
      <% end %>
    </div>
    <footer class="footer">
      <p>Copyright © 2019 TAKEYAMA INC All RIGHTS RESERVED.</p>
    </footer>
  </body>
</html>

app/views/tubuyakis/show.html.erb
<%= render 'form' %>